version: '3.7'

services:
  memcached:
    image: memcached:alpine
    networks:
      - back
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - back
    volumes:
      - ./data/db:/data/db
  node:
    image: saseul-core
    command: bin/start_node.sh
    networks:
      - back
      - front
    depends_on:
      - memcached
      - mongo
    volumes:
      - .:/app/saseul
      - ./data/logs:/var/log/saseul
    env_file: .env
  api:
    image: saseul-core
    networks:
      - back
      - front
    depends_on:
      - memcached
      - mongo
    volumes:
      - .:/app/saseul
      - ./data/logs:/var/log/saseul
    env_file: .env
  web:
    image: nginx:alpine
    networks:
      - front
    depends_on:
      - api
    ports:
      - 8080:80
    volumes:
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/saseul/public

networks:
  front:
  back:
