#!/usr/bin/env php

<?php

// const
define('SASEUL_DIR', dirname(__DIR__));
define('ROOT_DIR', __DIR__);

// autoload
require_once(SASEUL_DIR . '/vendor/autoload.php');


// set ini
posix_setgid(getmygid());
posix_setuid(getmyuid());

use Saseul\Common\ScriptLoader;

// execute script
$scriptLoader = new ScriptLoader($argv);
$scriptLoader->main();
