#!/usr/bin/env php

<?php

# const
define('SASEUL_DIR', dirname(__DIR__));
define('ROOT_DIR', __DIR__);

# autoload;
require_once("autoload.php");

# set ini;
date_default_timezone_set('Asia/Seoul');
ini_set('memory_limit','1G');
posix_setgid(getmygid());
posix_setuid(getmyuid());

# execute script;
$scriptLoader = new \Saseul\Common\ScriptLoader($argv);
$scriptLoader->main();
