#!/usr/bin/env php

<?php

// const
define('SASEUL_DIR', dirname(__DIR__));
define('ROOT_DIR', __DIR__);

// autoload
require_once(SASEUL_DIR . '/vendor/autoload.php');

use Saseul\Common\DaemonLoader;

// run daemon;
$daemonLoader = new DaemonLoader();
$daemonLoader->main();
