#!/usr/bin/php
<?php

# const
define('SASEUL_DIR', dirname(__DIR__));
define('ROOT_DIR', __DIR__);

# autoload;
require_once("autoload.php");

# set ini;
date_default_timezone_set('Asia/Seoul');
ini_set('memory_limit','1G');

# run daemon;
$daemonLoader = new \Saseul\Common\DaemonLoader();
$daemonLoader->main();
